"""Deployment secrets: generated once, then handed to each service on a need-to-know basis.

The ``secrets`` job runs before anything else (``python -m perimeter.tools.secrets /secrets``) and
owns one volume::

    store/      the canonical values; readable by this job only and never mounted elsewhere
    db/         PostgreSQL: its superuser password and SCRAM verifiers of the two login roles
    nats/       NATS: bcrypt hashes of the service users, included by the server config
    init/ api/ engine/ generator/
                plain values for exactly one service each, mounted read-only at /run/secrets

Every container mounts only its own directory (a volume ``subpath``), so a compromised api cannot
read the engine's broker password, and the database and the broker only ever hold hashes of the
passwords the services present. Nothing secret passes through environment variables, the compose
file or logs.

Runs are idempotent. Missing values are generated; existing values are never replaced, because
rotation must be a deliberate operation rather than a side effect of a restart. Every derived file
is checked against its source value and rewritten only when it is missing, stale or has drifted
permissions. If service files exist while their source values do not, the job stops instead of
issuing credentials that the database and broker would reject.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import os
import re
import secrets
import stat
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Protocol

import bcrypt
import structlog

from perimeter.ops.logging import configure_logging

log = structlog.get_logger(__name__)

STORE: Final = "store"
POSTGRES_GID: Final = 70
NATS_GID: Final = 10002
BCRYPT_ROUNDS: Final = 11
SCRAM_ITERATIONS: Final = 4096

type Values = Mapping[str, str]


class SecretsError(RuntimeError):
    """The volume is in a state the job must not paper over."""


@dataclass(frozen=True, slots=True)
class Secret:
    name: str
    entropy_bytes: int


# Random, URL-safe values: they are also used verbatim in configuration and HTTP headers.
SECRETS: Final = (
    Secret("database_superuser_password", 32),
    Secret("database_owner_password", 32),
    Secret("database_app_password", 32),
    Secret("session_secret", 48),
    Secret("ingest_token", 32),
    Secret("nats_init_password", 32),
    Secret("nats_api_password", 32),
    Secret("nats_engine_password", 32),
)

NATS_USERS: Final = ("init", "api", "engine")


class Content(Protocol):
    """How one file is derived from the canonical values, and how to tell it is still valid."""

    @property
    def sources(self) -> tuple[str, ...]: ...

    def render(self, values: Values) -> bytes: ...

    def current(self, existing: bytes, values: Values) -> bool: ...


@dataclass(frozen=True, slots=True)
class Copy:
    """The value itself, for a service that presents it."""

    secret: str

    @property
    def sources(self) -> tuple[str, ...]:
        return (self.secret,)

    def render(self, values: Values) -> bytes:
        return values[self.secret].encode()

    def current(self, existing: bytes, values: Values) -> bool:
        return hmac.compare_digest(existing, self.render(values))


@dataclass(frozen=True, slots=True)
class ScramVerifier:
    """A PostgreSQL SCRAM-SHA-256 verifier, so the database never stores the password."""

    secret: str

    @property
    def sources(self) -> tuple[str, ...]:
        return (self.secret,)

    def render(self, values: Values) -> bytes:
        return scram_sha256(values[self.secret]).encode()

    def current(self, existing: bytes, values: Values) -> bool:
        return scram_matches(existing.decode(errors="replace"), values[self.secret])


@dataclass(frozen=True, slots=True)
class NatsPasswords:
    """bcrypt hashes of the broker users, as variables the server configuration refers to."""

    users: tuple[str, ...]

    @property
    def sources(self) -> tuple[str, ...]:
        return tuple(nats_password_secret(user) for user in self.users)

    def render(self, values: Values) -> bytes:
        lines = [
            "# Generated by perimeter.tools.secrets: bcrypt hashes of the broker users' passwords.",
            "# The plaintext passwords exist only in each service's own secret directory.",
        ]
        for user in self.users:
            password = values[nats_password_secret(user)].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt(rounds=BCRYPT_ROUNDS)).decode()
            lines.append(f'{nats_variable(user)}: "{hashed}"')
        return ("\n".join(lines) + "\n").encode()

    def current(self, existing: bytes, values: Values) -> bool:
        hashes = parse_nats_passwords(existing.decode(errors="replace"))
        if set(hashes) != {nats_variable(user) for user in self.users}:
            return False
        return all(
            bcrypt.checkpw(
                values[nats_password_secret(user)].encode(), hashes[nats_variable(user)].encode()
            )
            for user in self.users
        )


@dataclass(frozen=True, slots=True)
class Consumer:
    """One service's directory. ``group`` names who may read it besides this job."""

    name: str
    group: str
    files: tuple[tuple[str, Content], ...]


LAYOUT: Final = (
    Consumer(
        "db",
        "postgres",
        (
            ("superuser_password", Copy("database_superuser_password")),
            ("perimeter.scram", ScramVerifier("database_owner_password")),
            ("perimeter_app.scram", ScramVerifier("database_app_password")),
        ),
    ),
    Consumer("nats", "nats", (("passwords.conf", NatsPasswords(NATS_USERS)),)),
    Consumer(
        "init",
        "self",
        (
            ("database_password", Copy("database_owner_password")),
            ("nats_password", Copy("nats_init_password")),
        ),
    ),
    Consumer(
        "api",
        "self",
        (
            ("database_password", Copy("database_app_password")),
            ("nats_password", Copy("nats_api_password")),
            ("session_secret", Copy("session_secret")),
            ("ingest_token", Copy("ingest_token")),
        ),
    ),
    Consumer(
        "engine",
        "self",
        (
            ("database_password", Copy("database_app_password")),
            ("nats_password", Copy("nats_engine_password")),
        ),
    ),
    Consumer("generator", "self", (("ingest_token", Copy("ingest_token")),)),
)


@dataclass(frozen=True, slots=True)
class Groups:
    """Numeric groups of the readers: the PostgreSQL and NATS images' users, and our own."""

    postgres: int
    nats: int
    own: int

    def of(self, consumer: Consumer) -> int:
        return {"postgres": self.postgres, "nats": self.nats}.get(consumer.group, self.own)


@dataclass(slots=True)
class Report:
    generated: list[str] = field(default_factory=list)
    written: list[str] = field(default_factory=list)
    repaired: list[str] = field(default_factory=list)


def nats_password_secret(user: str) -> str:
    return f"nats_{user}_password"


def nats_variable(user: str) -> str:
    return f"{user.upper()}_PASSWORD"


_NATS_ASSIGNMENT = re.compile(
    r'^(?P<name>[A-Z][A-Z0-9_]*): "(?P<hash>\$2[aby]\$\d\d\$[./0-9A-Za-z]{53})"$'
)


def parse_nats_passwords(text: str) -> dict[str, str]:
    """Variable name -> bcrypt hash, from a file written by :class:`NatsPasswords`."""
    hashes: dict[str, str] = {}
    for line in text.splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        match = _NATS_ASSIGNMENT.match(line)
        if match is None:
            return {}
        hashes[match["name"]] = match["hash"]
    return hashes


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode()


def _scram_keys(password: str, salt: bytes, iterations: int) -> tuple[bytes, bytes]:
    # PostgreSQL normalises passwords with SASLprep; URL-safe ASCII passwords are left unchanged.
    salted = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, iterations)
    stored_key = hashlib.sha256(hmac.digest(salted, b"Client Key", "sha256")).digest()
    server_key = hmac.digest(salted, b"Server Key", "sha256")
    return stored_key, server_key


def scram_sha256(
    password: str, *, salt: bytes | None = None, iterations: int = SCRAM_ITERATIONS
) -> str:
    """PostgreSQL's stored form of a password (RFC 5802/7677): ``SCRAM-SHA-256$i:salt$sk:svk``."""
    salt = salt if salt is not None else os.urandom(16)
    stored_key, server_key = _scram_keys(password, salt, iterations)
    return f"SCRAM-SHA-256${iterations}:{_b64(salt)}${_b64(stored_key)}:{_b64(server_key)}"


_SCRAM = re.compile(
    r"^SCRAM-SHA-256\$(?P<iterations>\d+):(?P<salt>[A-Za-z0-9+/=]+)"
    r"\$(?P<stored>[A-Za-z0-9+/=]+):(?P<server>[A-Za-z0-9+/=]+)$"
)


def scram_matches(verifier: str, password: str) -> bool:
    match = _SCRAM.match(verifier.strip())
    if match is None:
        return False
    salt = base64.b64decode(match["salt"])
    stored_key, server_key = _scram_keys(password, salt, int(match["iterations"]))
    return hmac.compare_digest(_b64(stored_key), match["stored"]) and hmac.compare_digest(
        _b64(server_key), match["server"]
    )


def _read(path: Path) -> bytes | None:
    """File content, or ``None`` if absent. Symbolic links are refused, never followed."""
    try:
        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    except FileNotFoundError:
        return None
    except OSError as exc:
        msg = f"cannot read {path}: {exc.strerror}"
        raise SecretsError(msg) from exc
    with os.fdopen(fd, "rb") as file:
        if not stat.S_ISREG(os.fstat(file.fileno()).st_mode):
            msg = f"{path} is not a regular file"
            raise SecretsError(msg)
        return file.read()


def _write(path: Path, content: bytes, *, mode: int, gid: int) -> None:
    """Replace ``path`` atomically; the new file is never visible with the wrong owner or mode."""
    temporary = path.with_name(f".{path.name}.{secrets.token_hex(4)}.tmp")
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        with os.fdopen(fd, "wb") as file:
            file.write(content)
            file.flush()
            os.fsync(file.fileno())
            os.fchown(file.fileno(), -1, gid)
            os.fchmod(file.fileno(), mode)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    _fsync_directory(path.parent)


def _fsync_directory(directory: Path) -> None:
    fd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _is_directory(path: Path) -> bool:
    """Whether ``path`` is a real directory; anything else in its place is an error."""
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    if not stat.S_ISDIR(info.st_mode):
        msg = f"{path} exists but is not a directory"
        raise SecretsError(msg)
    return True


def _ensure_directory(path: Path, *, mode: int, gid: int) -> bool:
    """Create a directory, or repair an existing one; returns whether a repair was needed."""
    if not _is_directory(path):
        path.mkdir(mode=mode)
        os.chown(path, -1, gid)
        path.chmod(mode)
        return False
    return _repair(path, path.lstat(), mode=mode, gid=gid)


def _repair(path: Path, info: os.stat_result, *, mode: int, gid: int) -> bool:
    changed = False
    if info.st_gid != gid:
        os.chown(path, -1, gid, follow_symlinks=False)
        changed = True
    if stat.S_IMODE(info.st_mode) != mode:
        path.chmod(mode)
        changed = True
    return changed


def _sweep_temporaries(directory: Path) -> None:
    """Remove half-written files left behind by an interrupted run."""
    for leftover in directory.glob(".*.tmp"):
        leftover.unlink(missing_ok=True)


def _stored_value(path: Path, raw: bytes) -> str:
    try:
        value = raw.decode("ascii").strip()
    except UnicodeDecodeError as exc:
        msg = f"{path} is not a generated value (not ASCII)"
        raise SecretsError(msg) from exc
    if not value or any(ch.isspace() for ch in value):
        msg = f"{path} is empty or malformed; restore it rather than generating a new value"
        raise SecretsError(msg)
    return value


def _check_no_orphans(root: Path, layout: Sequence[Consumer], missing: set[str]) -> None:
    """Refuse to mint a value that existing service files were derived from."""
    orphans = sorted(
        f"{consumer.name}/{filename}"
        for consumer in layout
        for filename, content in consumer.files
        if missing.intersection(content.sources) and (root / consumer.name / filename).exists()
    )
    if orphans:
        msg = (
            f"service secrets {', '.join(orphans)} exist but the values they were derived from "
            f"are missing from {root / STORE}; refusing to issue credentials the database and "
            "broker would reject. Restore the volume, or remove it together with the data "
            "volumes to start over."
        )
        raise SecretsError(msg)


def reconcile(
    root: Path,
    groups: Groups,
    *,
    layout: Sequence[Consumer] = LAYOUT,
    token: Callable[[int], str] = secrets.token_urlsafe,
) -> Report:
    """Bring ``root`` to the target layout without ever replacing an existing value."""
    report = Report()
    if not _is_directory(root):
        msg = f"{root} does not exist; mount the secrets volume there"
        raise SecretsError(msg)
    store = root / STORE

    values: dict[str, str] = {}
    if _is_directory(store):
        for secret in SECRETS:
            raw = _read(store / secret.name)
            if raw is not None:
                values[secret.name] = _stored_value(store / secret.name, raw)
    missing = {secret.name for secret in SECRETS} - values.keys()
    _check_no_orphans(root, layout, missing)

    _ensure_directory(store, mode=0o700, gid=groups.own)
    _sweep_temporaries(store)
    for secret in SECRETS:
        path = store / secret.name
        if secret.name in missing:
            values[secret.name] = token(secret.entropy_bytes)
            _write(path, values[secret.name].encode(), mode=0o400, gid=groups.own)
            report.generated.append(secret.name)
        elif _repair(path, path.lstat(), mode=0o400, gid=groups.own):
            report.repaired.append(f"{STORE}/{secret.name}")

    for consumer in layout:
        shared = consumer.group != "self"
        gid = groups.of(consumer)
        directory = root / consumer.name
        if _ensure_directory(directory, mode=0o750 if shared else 0o700, gid=gid):
            report.repaired.append(consumer.name)
        _sweep_temporaries(directory)
        file_mode = 0o440 if shared else 0o400
        for filename, content in consumer.files:
            path = directory / filename
            relative = f"{consumer.name}/{filename}"
            existing = _read(path)
            if existing is None or not content.current(existing, values):
                _write(path, content.render(values), mode=file_mode, gid=gid)
                report.written.append(relative)
            elif _repair(path, path.lstat(), mode=file_mode, gid=gid):
                report.repaired.append(relative)
    return report


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m perimeter.tools.secrets",
        description="Generate deployment secrets once and lay them out per service.",
    )
    parser.add_argument("root", type=Path, help="directory of the secrets volume")
    parser.add_argument(
        "--postgres-gid", type=int, default=POSTGRES_GID, help="group of the database server"
    )
    parser.add_argument("--nats-gid", type=int, default=NATS_GID, help="group of the broker")
    args = parser.parse_args(argv)

    configure_logging(service="secrets", level=os.environ.get("LOG_LEVEL", "INFO"))
    os.umask(0o077)
    groups = Groups(postgres=args.postgres_gid, nats=args.nats_gid, own=os.getgid())
    try:
        report = reconcile(args.root, groups)
    except (SecretsError, OSError) as exc:
        log.error("secrets.failed", error=str(exc))
        return 1
    if report.generated:
        log.info("secrets.generated", names=report.generated)
    if "ingest_token" in report.generated:
        log.info(
            "secrets.ingest_token_location",
            detail="load generators read it from /run/secrets/ingest_token in their container",
            host_command="docker compose exec api cat /run/secrets/ingest_token",
        )
    if report.written or report.repaired:
        log.info("secrets.laid_out", written=report.written, repaired=report.repaired)
    log.info(
        "secrets.ready",
        generated=len(report.generated),
        written=len(report.written),
        repaired=len(report.repaired),
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
